config/routes.rb
Rails.application.routes.draw do
  resources :tiny_urls, only: [:index, :create], param: :mini_url

  get ':mini_url', to: 'tiny_urls#show', param: :mini_url, as: :show
  get ':mini_url/info', to: 'tiny_urls#info', param: :mini_url, as: :info

  root to: 'tiny_urls#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tiny_url.rb
class TinyUrl < ApplicationRecord
  has_many :url_visitors, dependent: :destroy

  validates_presence_of :mini_url, :original_url

  before_validation :build_mini_url

  def formatted_original_url
    url = URI.parse(original_url)
    if url.scheme.present?
      original_url
    else
      'http://' + url.path
    end
  end

  private

    def build_mini_url
      loop do
        self.mini_url = SecureRandom.hex(3)
        break if TinyUrl.where(mini_url: self.mini_url).empty?
      end
    end
end

app/models/url_visitor.rb
class UrlVisitor < ApplicationRecord
  belongs_to :tiny_url

  validates_presence_of :ip, :tiny_url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tiny_urls_controller.rb
class TinyUrlsController < ApplicationController

  def index
  end

  def create
    url = tiny_url_params[:original_url]
    if url.present?
      tiny_url = TinyUrl.create(original_url: url)
      if tiny_url.persisted?
        redirect_to info_path(tiny_url.mini_url), notice: 'Successfully created an tiny url!'
      else
        redirect_to root_path(original_url: url), error: tiny_url.errors.full_messages.join(', ')
      end
    else
      redirect_to root_path(original_url: url), alert: 'You must provide a URL.'
    end
  end

  def show
    @tiny_url = TinyUrl.find_by(mini_url: params[:mini_url])
    @tiny_url.url_visitors.create(tiny_url: @tiny_url, ip: request.remote_ip)

    redirect_to @tiny_url.formatted_original_url
  end

  def info
    @tiny_url = TinyUrl.includes(:url_visitors).find_by(mini_url: params[:mini_url])

    unless @tiny_url.present?
      redirect_to root_path, alert: 'URL not found.'
    end
  end

  private

    def tiny_url_params
      params.require(:tiny_url).permit(:original_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TinyurlClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% if flash.count > 0 %>
  <div class="flash-messages-container">
    <% flash.each do |flash_type, msg| %>
      <div class="alert alert-dismissible fade show" role="alert">
        <p class="flash-body mb-1"><%= msg.html_safe %></p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/tiny_urls/index.html.erb
<%= render 'shared/flash_messages' %>

<h2>Enter a URL to be tinified!</h2>

<%= form_for TinyUrl.new, url: tiny_urls_path, method: :post do |f| %>
  <%= f.text_field :original_url, value: params[:original_url] || '' %>
  <%= f.submit 'GO' %>
<% end %>

app/views/tiny_urls/info.html.erb
<%= render 'shared/flash_messages' %>

<h2>Tiny URL Info:</h2>

<ul>
  <li>Tiny url: <%= link_to show_url(@tiny_url.mini_url), show_url(@tiny_url.mini_url), target: :_blank %></li>
  <li>Original url: <%= link_to @tiny_url.formatted_original_url, @tiny_url.formatted_original_url %></li>
</ul>

<h2>URL Visitors</h2>
<ul>
  <% if @tiny_url.url_visitors.present? %>
  <% @tiny_url.url_visitors.each do |visitor| %>
    <li>IP Address: <%= visitor.ip %>on <%= visitor.created_at.strftime('%d %b %Y, %H:%M %Z') %></li>
  <% end %>
  <% else %>
    <li>No visitors yet!</li>
  <% end %>
</ul>